// hd-web-kb.js — 手工维护的学习页英文正文 + 起源(About)。不会被生成器覆盖。
// EN prose distilled & rewritten from 99_RefBooks/_notes/web (humdes-*, ihds-newcomers-en, origin-zh).
export const EN_TEXT = {
  types: {
    Generator: 'Generators are the life force of the world — about a third of everyone you meet. The Sacral center hums with renewable energy, but it only switches on in response to something real. The aura is open and enveloping, drawing life toward you, which is why the strategy is to wait to respond rather than chase. In practice: notice what lights you up in daily encounters — an offer, a question, a gut "uh-huh" — and commit your energy there. Work that satisfies leaves you pleasantly spent at night; work you initiated from the mind breeds frustration, the classic Generator signal to step back and listen to the body again.',
    'Manifesting Generator': 'Manifesting Generators are Generators with a motor wired straight to the Throat, so once the Sacral says yes, things move fast. They compress steps, juggle several passions at once, and often look impatient to everyone else. The aura is the same open, enveloping Generator field, so the rule still holds: respond first, then inform the people your speed will affect before you leap. Skipping steps is part of the design — some get revisited later, and that is fine. Frustration plus anger is the sign of forcing; satisfaction comes from letting the gut choose what deserves that famous multi-track energy.',
    Manifestor: 'Manifestors are the rare initiators — the only type designed to act first without waiting for anything outside themselves. The aura is closed and repelling, built to clear a path for impact, which is also why others often find them hard to read and try to control them. The strategy is simply to inform: tell the people in your impact zone before you act, not to ask permission but to dissolve resistance in advance. Energy arrives in powerful bursts rather than a steady hum, so rest between initiations matters. Anger flags interference; peace is the signature of a Manifestor moving freely.',
    Projector: 'Projectors are here to guide energy, not to supply it. With no consistent motor of their own, they read other people with a focused, penetrating aura that sees deeply into one person at a time. The catch: guidance only lands when it is wanted, so the strategy is to wait for invitation — for the big things like love, career, and direction. Uninvited advice, however brilliant, breeds bitterness and rejection. Success comes from studying a system deeply, becoming recognizable for that mastery, and managing energy honestly: borrow the buzz of Generator auras by day, but sleep and recharge alone before exhaustion sets in.',
    Reflector: 'Reflectors are the rarest design — every center open, a lunar being in a solar world. The aura is resistant and sampling: it tastes the people and places around it and mirrors the health of the community back to it. Nothing about a Reflector is fixed; consistency comes from the Moon, which replays their whole chart roughly every 29.5 days. Hence the strategy: give a major decision a full lunar cycle, talking it through with trusted sounding boards until clarity settles. The right place is everything — in a nourishing environment a Reflector feels delightful surprise; in the wrong one, chronic disappointment.'
  },
  authorities: {
    Emotional: 'The defined Solar Plexus runs in waves — hope to pain and back — and truth only shows itself across the whole ride. There is no clarity in the now: a yes that feels thrilling tonight may feel wrong by Thursday. The practice is to delay, sleep on it, and revisit the question at several points on the wave until a calm, repeatable answer remains. Roughly half of humanity carries this design, so "let me get back to you" is one of the most honest sentences in the world.',
    Sacral: 'Decisions live in the gut, not the head. The Sacral responds in the moment with an audible or felt uh-huh (yes), uh-uh (no), or silence (nothing here). It answers best when life — or a friend — asks direct yes/no questions out loud. The response is about energy: does my life force want to engage this, right now? Trusting that sound before the mind starts negotiating is the whole discipline of Sacral authority.',
    Splenic: 'The Spleen speaks once, quietly, in the immediate moment — a flash of knowing about safety, health, and timing. It does not repeat itself and it will not argue with your mind, which is usually louder and always later. Living this authority means acting on the first subtle hit — the hesitation at the door, the instant ease with a stranger — and discovering afterward why it was right. Spontaneous, existential, and easily drowned out by overthinking.',
    Ego: 'Will-based authority is rare: the Heart/Ego center decides through what it genuinely wants and is willing to commit to. The honest question is "what is in this for me, and will I see it through?" — selfish-sounding, but it is the design working correctly. The voice often slips out unguarded: "I want…", "I will…". Promises made from real desire get kept; promises made to please others drain willpower and break.',
    SelfProjected: 'Decisions surface through your own voice. With the G center projected to the Throat, truth comes out when you talk about the decision — not by weighing pros and cons but by hearing yourself. The compass questions are about identity and direction: will this make me happy, does this feel like me, is this heading where I am going? Find trusted listeners who reflect rather than advise, and trust the first thing you hear yourself say.',
    Mental: 'No motor below the Throat is defined, so the truth is not inside the body in the usual sense — it emerges in conversation, in the right environments. Mental (environmental) authority means talking decisions through with sounding boards, not for their opinions but to hear and feel your own recognition as the words land. Place matters enormously: the same question answers itself differently in nourishing versus draining surroundings, so move, discuss, and let clarity assemble over time.',
    Lunar: 'The Reflector authority: wait a full lunar cycle — about 29.5 days — before any major commitment. With no center defined, each day the Moon lights up a different part of the chart, offering a different vantage point. Over a month every perspective is sampled, and a stable knowing crystallizes underneath the changing weather. Talk it out with trusted people along the way, resist the pressure of other people’s urgency, and let time be the decision-maker.'
  },
  centers: {
    Head: { defined: 'A consistent source of mental pressure and inspiration: questions bubble up from within, on their own schedule. You inspire others simply by wondering aloud. The pressure to answer is real but is fuel for contemplation, not a deadline — let questions ripen instead of demanding instant resolution.', open: 'Inspiration flows in from everyone around you, which makes you wonderfully receptive — and vulnerable to thinking about questions that are not yours. The not-self trap is chasing answers to borrowed puzzles. Wisdom here is savoring who and what is genuinely inspiring without making every passing question urgent.' },
    Ajna: { defined: 'A fixed way of conceptualizing: your mind processes and organizes ideas in its own reliable style — logical, abstract, or knowing. Concepts feel certain, which is a gift for research and teaching, and a trap if certainty hardens into "my way is the truth." Opinions are for sharing, not for deciding your life.', open: 'Thoughts and frameworks stay fluid; you can see a question from every side and genuinely change your mind. The pressure is pretending certainty to seem reliable. The wisdom is intellectual flexibility — recognizing which concepts are valuable without needing to be fixed on any of them.' },
    Throat: { defined: 'A consistent voice: expression and, with a motor attached, action flow in a reliable style. Words tend to land because they come out the same way every time. The art is timing — even a defined Throat works best when someone is actually listening, rather than talking to secure attention.', open: 'Speech adapts to the room — who you are talking to shapes how the words come out, and silence can stretch until the moment is right. The not-self pushes to talk first and attract attention. Trusted timing makes you a superb spokesperson for others; when you are invited to speak, it carries.' },
    G: { defined: 'A fixed sense of identity and direction: love, self, and trajectory feel internally anchored, regardless of surroundings. People orient themselves around your steadiness. The work is simply being who you are without apology — your direction does not require consensus, only expression.', open: 'Identity and direction are fluid: place and people shape who you feel yourself to be. This is not brokenness — it is sensitivity. The guiding rule: if the place is right, the people will be right. Wrong environments produce lostness; right ones let you taste many selves wisely, without clinging to any fixed "me."' },
    Heart: { defined: 'Reliable willpower in a world that mostly runs without it. You can make promises and keep them, and your sense of worth is tied to delivering. The design needs cycles of work and genuine rest — and deals stated out loud. Say what you want plainly; unspoken bargains breed resentment.', open: 'There is no consistent willpower to push with, and no need to prove anything — though the not-self insists otherwise, making promises to demonstrate worth. Vows made under pressure break and cost self-esteem. Freedom here is refusing comparison contests and letting value rest on design, not on willful effort.' },
    Sacral: { defined: 'The renewable battery of life-force and fertility, responding moment to moment with its grunts of yes and no. Energy regenerates when spent on the right things — satisfaction is the proof. The discipline is honoring the response: degeneration begins when the mind overrides the gut and commits the battery elsewhere.', open: 'No consistent access to work-force energy: you run on borrowed Sacral buzz and rarely know when enough is enough. The classic trap is overworking to keep up with Generators until collapse. Wisdom is pacing — knowing the community’s energy without matching it, and resting before the body forces the issue.' },
    SolarPlexus: { defined: 'Emotions move in waves — hope to pain, ecstasy to despair — with no reason required. The wave is chemistry, not a problem to fix. Clarity arrives over time, never in the spike of the moment. Lived well, this is the source of depth, poetry, and ripened decisions; lived fast, it is drama.', open: 'You feel other people’s emotions and amplify them, often louder than the original. The not-self strategy is avoiding confrontation and truth to keep everyone comfortable — being "nice" at any cost. Wisdom is becoming a clear screen: identifying whose feelings these are, stepping out of the wave, and choosing honestly.' },
    Spleen: { defined: 'A steady immune awareness: instinct, timing, and well-being hum in the background, speaking once in the moment. Your presence literally feels reassuring to others. The responsibility is respecting your own alarms — the quiet "not this" — instead of letting fear be talked over by logic or politeness.', open: 'Sensitive to everyone’s fears and to the feeling of safety itself, you may hold on to what feels secure — jobs, relationships, habits — long past their health. Spontaneous letting-go is hard; that is by design. The wisdom is discerning which fears are real and whose they are, then releasing on your own timing.' },
    Root: { defined: 'A consistent engine of adrenalized pressure: stress is fuel, and you process it in your own pulse — pressure on, pressure off. Drive feels natural rather than frantic. The craft is aiming the fuel at what response or strategy actually selects, instead of letting raw momentum pick the target.', open: 'The world’s hurry floods in: open Roots feel perpetually behind, racing to clear the to-do list so the pressure will finally stop — but it never does, because the pressure is borrowed. Freedom begins when speed is no longer mistaken for necessity. Done wisely, you sense exactly where pressure is worth engaging.' }
  },
  profiles: {
    '1/3': 'The Investigator/Martyr builds life on studied foundations, then stress-tests them personally. Research first, leap second, discover what breaks, adjust. Nothing is wasted: every "failed" experiment becomes authority. Security comes from knowing the material; resilience comes from accepting that trial and error is the method, not a flaw.',
    '1/4': 'The Investigator/Opportunist studies until the ground is solid, then shares the findings through a warm, loyal network. Mastery comes first, influence travels through friendship. Opportunities arrive from people who already know and trust you — so the foundation must be ready before the door opens, because this design externalizes what it has internalized.',
    '2/4': 'The Hermit/Opportunist alternates between precious solitude and the pull of the network. Natural talent develops alone, unwatched, until others recognize it and call it out. The right call, from the right people, is worth answering; the wrong demands feel like intrusion. Protect hermit time — it is where the gift ripens.',
    '2/5': 'The Hermit/Heretic would rather be left alone, yet projections keep arriving: others see a savior and call the 2/5 out to fix things. When the call is genuine and the talent real, the practical solutions are remarkable. When it is not, withdraw without guilt — managing expectations is this profile’s survival skill.',
    '3/5': 'The Martyr/Heretic is the great experimenter under the heaviest projections. Life supplies collisions — things break, bonds end, plans fail — and each yields concrete know-how that others eventually depend on. The world projects "fixer" onto the 3/5; delivering practical solutions earns lasting respect, while blame for failed projections must simply roll off.',
    '3/6': 'The Martyr/Role Model lives a double rhythm: a personality that learns by bumping into life, atop a soul moving through three phases — chaotic experimentation till about 30, observation from the roof until 50, then engaged wisdom. Early turbulence is curriculum, not error. With time, hard-won discoveries mature into example.',
    '4/6': 'The Opportunist/Role Model influences through relationships while gradually becoming an example. The 4 needs its trusted circle — opportunities and meaning flow through people — while the 6 climbs through trial, retreat, and return. Friendliness in the foreground, authority ripening in the background; by the second half of life, the network listens.',
    '4/1': 'The Opportunist/Investigator is the single fixed-fate profile: a foundation of study expressed through a stable network, running on rails that barely bend. Strength lies in transmitting one well-built truth to people who trust you. Honor the fixedness — pressure to be flexible about essentials breaks this design rather than improving it.',
    '5/1': 'The Heretic/Investigator is the practical general: others project leadership and rescue onto the 5, and the deep first-line research is what lets the reputation survive contact with reality. Universalize solutions when truly prepared and called; otherwise the projection field turns. Solid homework plus chosen battles equals lasting influence.',
    '5/2': 'The Heretic/Hermit attracts grand projections while genuinely preferring to be left alone with its own gifts. Others insist you lead; you suspect they see someone who is not quite you. When a call matches the real talent underneath, answering it universalizes something valuable. The rest of the time, guard the hermitage.',
    '6/2': 'The Role Model/Hermit moves through the three-phase arc — experiment, withdraw to the roof, re-emerge — carrying a natural, unstudied gift. People sense the aloof wisdom and call it out. Trust matters more than technique here: life is the demonstration, and the example only convinces when it is genuinely lived.',
    '6/3': 'The Role Model/Martyr is the perpetual learner whose wisdom is bought with mileage: even in the observation phase, the third line keeps colliding with reality, making and breaking bonds, testing what the sixth line will one day model. Optimism plus scar tissue. The example such a life eventually sets is unimpeachably earned.'
  },
  definitions: {
    Single: 'All defined centers are wired into one continuous circuit: inner processing is self-contained, quick to settle, and consistent. Single definitions feel whole on their own and do not need others to complete a thought — the lesson is patience with people who process in pieces.',
    Split: 'Definition lives in two islands, and the gap between them is felt as "something missing." Specific people or gates bridge the split, which makes certain company feel electric and necessary. Healthy use: let bridges bring perspective without outsourcing decisions to whoever happens to connect the halves.',
    'Triple Split': 'Three separate areas of definition seek connection. Different settings and different people light up different bridges, so clarity assembles over time and movement — one conversation rarely settles it. Varied environments are nourishing; being stuck with one fixed bridge person all day scrambles the processing.',
    'Quadruple Split': 'Four defined islands — a rare, heavily defined design with fixed, complex processing. So much is already wired in that integrating it takes time; decisions deserve slowness and stable routine. Others may find the consistency formidable. The trap is letting one bridging person dominate the whole system.',
    None: 'No centers are defined at all — the Reflector configuration. Nothing fixed inside means everything is sampled: people, places, and lunar transits flow through and are mirrored back. Consistency comes from the Moon’s cycle rather than from inner wiring, so time and right environment are the real authorities.'
  }
};

export const ORIGIN = {
  zh: '人类图由 Ra Uru Hu（原名 Alan Robert Krakower）创立。1987 年初——恰逢超新星 1987A 出现之际——他在西班牙伊维萨岛经历了连续八天八夜的强烈传讯体验，接收到这套体系的完整结构，随后用数十年时间整理、验证并系统化。人类图把四大古老智慧——易经六十四卦、西洋占星、卡巴拉生命之树、印度脉轮——与遗传学、天文学等现代科学熔于一炉，生成每个人独有的「人体图」。它不谈性格标签，而专注运作机制：以「策略」回应世界、以「内在权威」做出决定，本质是一套帮助人摆脱「非自己」制约的实验性工具。Ra 此后创办教学体系并培养分析师，使这门知识从伊维萨的八个夜晚走向全球。它不要求相信，只邀请亲自实验。',
  en: 'Human Design began in early 1987, when Ra Uru Hu — born Alan Robert Krakower — underwent an intense eight-day, eight-night encounter on the island of Ibiza, coinciding with the light of supernova 1987A reaching Earth. In that transmission he received the mechanics of what became the BodyGraph: a synthesis folding the I Ching’s 64 hexagrams, Western astrology, the Kabbalistic Tree of Life, and the Hindu chakra system into one framework, grounded in modern ideas from genetics, astronomy, and neutrino physics. Ra spent the following decades testing, refining, and teaching the system, founding schools and training analysts so the knowledge could spread worldwide. Human Design calls itself a self-discovery tool for the 21st century, yet it asks for no belief: each chart is an invitation to a personal experiment — follow your Strategy, honor your inner Authority, and verify in your own life whether the mechanics hold.'
};
