/* places.js — 出生地搜索精选城市表（window.HD_PLACES）
   条目 = [enCity, zhCity, enCountry, zhCountry, IANA tz]
   中国大陆官方统一 Asia/Shanghai；区县级细分走 cn-pca.json 三级联想/滚轮。 */
window.HD_PLACES = [
  // ── 中国大陆主要城市 ──
  ['Beijing','北京','China','中国','Asia/Shanghai'],
  ['Shanghai','上海','China','中国','Asia/Shanghai'],
  ['Guangzhou','广州','China','中国','Asia/Shanghai'],
  ['Shenzhen','深圳','China','中国','Asia/Shanghai'],
  ['Chengdu','成都','China','中国','Asia/Shanghai'],
  ['Chongqing','重庆','China','中国','Asia/Shanghai'],
  ['Wuhan','武汉','China','中国','Asia/Shanghai'],
  ["Xi'an",'西安','China','中国','Asia/Shanghai'],
  ['Hangzhou','杭州','China','中国','Asia/Shanghai'],
  ['Nanjing','南京','China','中国','Asia/Shanghai'],
  ['Suzhou','苏州','China','中国','Asia/Shanghai'],
  ['Tianjin','天津','China','中国','Asia/Shanghai'],
  ['Qingdao','青岛','China','中国','Asia/Shanghai'],
  ['Jinan','济南','China','中国','Asia/Shanghai'],
  ['Changsha','长沙','China','中国','Asia/Shanghai'],
  ['Zhengzhou','郑州','China','中国','Asia/Shanghai'],
  ['Hefei','合肥','China','中国','Asia/Shanghai'],
  ['Nanchang','南昌','China','中国','Asia/Shanghai'],
  ['Fuzhou','福州','China','中国','Asia/Shanghai'],
  ['Xiamen','厦门','China','中国','Asia/Shanghai'],
  ['Shenyang','沈阳','China','中国','Asia/Shanghai'],
  ['Dalian','大连','China','中国','Asia/Shanghai'],
  ['Changchun','长春','China','中国','Asia/Shanghai'],
  ['Harbin','哈尔滨','China','中国','Asia/Shanghai'],
  ['Shijiazhuang','石家庄','China','中国','Asia/Shanghai'],
  ['Taiyuan','太原','China','中国','Asia/Shanghai'],
  ['Hohhot','呼和浩特','China','中国','Asia/Shanghai'],
  ['Chifeng','赤峰','China','中国','Asia/Shanghai'],
  ['Nanning','南宁','China','中国','Asia/Shanghai'],
  ['Haikou','海口','China','中国','Asia/Shanghai'],
  ['Guiyang','贵阳','China','中国','Asia/Shanghai'],
  ['Kunming','昆明','China','中国','Asia/Shanghai'],
  ['Lhasa','拉萨','China','中国','Asia/Shanghai'],
  ['Lanzhou','兰州','China','中国','Asia/Shanghai'],
  ['Xining','西宁','China','中国','Asia/Shanghai'],
  ['Yinchuan','银川','China','中国','Asia/Shanghai'],
  ['Urumqi','乌鲁木齐','China','中国','Asia/Shanghai'],
  // ── 港澳台 ──
  ['Hong Kong','香港','China','中国','Asia/Hong_Kong'],
  ['Macau','澳门','China','中国','Asia/Macau'],
  ['Taipei','台北','Taiwan','台湾','Asia/Taipei'],
  ['Kaohsiung','高雄','Taiwan','台湾','Asia/Taipei'],
  ['Taichung','台中','Taiwan','台湾','Asia/Taipei'],
  // ── 亚洲 ──
  ['Tokyo','东京','Japan','日本','Asia/Tokyo'],
  ['Osaka','大阪','Japan','日本','Asia/Tokyo'],
  ['Seoul','首尔','South Korea','韩国','Asia/Seoul'],
  ['Singapore','新加坡','Singapore','新加坡','Asia/Singapore'],
  ['Bangkok','曼谷','Thailand','泰国','Asia/Bangkok'],
  ['Kuala Lumpur','吉隆坡','Malaysia','马来西亚','Asia/Kuala_Lumpur'],
  ['Jakarta','雅加达','Indonesia','印度尼西亚','Asia/Jakarta'],
  ['Manila','马尼拉','Philippines','菲律宾','Asia/Manila'],
  ['Hanoi','河内','Vietnam','越南','Asia/Ho_Chi_Minh'],
  ['Ho Chi Minh City','胡志明市','Vietnam','越南','Asia/Ho_Chi_Minh'],
  ['Phnom Penh','金边','Cambodia','柬埔寨','Asia/Phnom_Penh'],
  ['Yangon','仰光','Myanmar','缅甸','Asia/Yangon'],
  ['Kathmandu','加德满都','Nepal','尼泊尔','Asia/Kathmandu'],
  ['New Delhi','新德里','India','印度','Asia/Kolkata'],
  ['Mumbai','孟买','India','印度','Asia/Kolkata'],
  ['Colombo','科伦坡','Sri Lanka','斯里兰卡','Asia/Colombo'],
  ['Karachi','卡拉奇','Pakistan','巴基斯坦','Asia/Karachi'],
  ['Dubai','迪拜','UAE','阿联酋','Asia/Dubai'],
  ['Riyadh','利雅得','Saudi Arabia','沙特','Asia/Riyadh'],
  ['Tel Aviv','特拉维夫','Israel','以色列','Asia/Jerusalem'],
  ['Istanbul','伊斯坦布尔','Turkey','土耳其','Europe/Istanbul'],
  ['Almaty','阿拉木图','Kazakhstan','哈萨克斯坦','Asia/Almaty'],
  ['Ulaanbaatar','乌兰巴托','Mongolia','蒙古','Asia/Ulaanbaatar'],
  // ── 欧洲 ──
  ['London','伦敦','UK','英国','Europe/London'],
  ['Paris','巴黎','France','法国','Europe/Paris'],
  ['Berlin','柏林','Germany','德国','Europe/Berlin'],
  ['Munich','慕尼黑','Germany','德国','Europe/Berlin'],
  ['Frankfurt','法兰克福','Germany','德国','Europe/Berlin'],
  ['Madrid','马德里','Spain','西班牙','Europe/Madrid'],
  ['Barcelona','巴塞罗那','Spain','西班牙','Europe/Madrid'],
  ['Rome','罗马','Italy','意大利','Europe/Rome'],
  ['Milan','米兰','Italy','意大利','Europe/Rome'],
  ['Amsterdam','阿姆斯特丹','Netherlands','荷兰','Europe/Amsterdam'],
  ['Brussels','布鲁塞尔','Belgium','比利时','Europe/Brussels'],
  ['Zurich','苏黎世','Switzerland','瑞士','Europe/Zurich'],
  ['Geneva','日内瓦','Switzerland','瑞士','Europe/Zurich'],
  ['Vienna','维也纳','Austria','奥地利','Europe/Vienna'],
  ['Prague','布拉格','Czechia','捷克','Europe/Prague'],
  ['Warsaw','华沙','Poland','波兰','Europe/Warsaw'],
  ['Budapest','布达佩斯','Hungary','匈牙利','Europe/Budapest'],
  ['Stockholm','斯德哥尔摩','Sweden','瑞典','Europe/Stockholm'],
  ['Oslo','奥斯陆','Norway','挪威','Europe/Oslo'],
  ['Copenhagen','哥本哈根','Denmark','丹麦','Europe/Copenhagen'],
  ['Helsinki','赫尔辛基','Finland','芬兰','Europe/Helsinki'],
  ['Athens','雅典','Greece','希腊','Europe/Athens'],
  ['Lisbon','里斯本','Portugal','葡萄牙','Europe/Lisbon'],
  ['Dublin','都柏林','Ireland','爱尔兰','Europe/Dublin'],
  ['Moscow','莫斯科','Russia','俄罗斯','Europe/Moscow'],
  ['Kyiv','基辅','Ukraine','乌克兰','Europe/Kyiv'],
  // ── 美洲 ──
  ['New York','纽约','USA','美国','America/New_York'],
  ['Boston','波士顿','USA','美国','America/New_York'],
  ['Washington','华盛顿','USA','美国','America/New_York'],
  ['Miami','迈阿密','USA','美国','America/New_York'],
  ['Chicago','芝加哥','USA','美国','America/Chicago'],
  ['Houston','休斯顿','USA','美国','America/Chicago'],
  ['Dallas','达拉斯','USA','美国','America/Chicago'],
  ['Denver','丹佛','USA','美国','America/Denver'],
  ['Phoenix','凤凰城','USA','美国','America/Phoenix'],
  ['Los Angeles','洛杉矶','USA','美国','America/Los_Angeles'],
  ['San Francisco','旧金山','USA','美国','America/Los_Angeles'],
  ['Seattle','西雅图','USA','美国','America/Los_Angeles'],
  ['Honolulu','檀香山','USA','美国','Pacific/Honolulu'],
  ['Toronto','多伦多','Canada','加拿大','America/Toronto'],
  ['Montreal','蒙特利尔','Canada','加拿大','America/Toronto'],
  ['Vancouver','温哥华','Canada','加拿大','America/Vancouver'],
  ['Mexico City','墨西哥城','Mexico','墨西哥','America/Mexico_City'],
  ['Sao Paulo','圣保罗','Brazil','巴西','America/Sao_Paulo'],
  ['Rio de Janeiro','里约热内卢','Brazil','巴西','America/Sao_Paulo'],
  ['Buenos Aires','布宜诺斯艾利斯','Argentina','阿根廷','America/Argentina/Buenos_Aires'],
  ['Lima','利马','Peru','秘鲁','America/Lima'],
  ['Bogota','波哥大','Colombia','哥伦比亚','America/Bogota'],
  ['Santiago','圣地亚哥','Chile','智利','America/Santiago'],
  // ── 大洋洲 / 非洲 ──
  ['Sydney','悉尼','Australia','澳大利亚','Australia/Sydney'],
  ['Melbourne','墨尔本','Australia','澳大利亚','Australia/Melbourne'],
  ['Brisbane','布里斯班','Australia','澳大利亚','Australia/Brisbane'],
  ['Perth','珀斯','Australia','澳大利亚','Australia/Perth'],
  ['Auckland','奥克兰','New Zealand','新西兰','Pacific/Auckland'],
  ['Cairo','开罗','Egypt','埃及','Africa/Cairo'],
  ['Johannesburg','约翰内斯堡','South Africa','南非','Africa/Johannesburg'],
  ['Nairobi','内罗毕','Kenya','肯尼亚','Africa/Nairobi'],
  ['Lagos','拉各斯','Nigeria','尼日利亚','Africa/Lagos'],
  ['Casablanca','卡萨布兰卡','Morocco','摩洛哥','Africa/Casablanca'],
];
